apiVersion: v1
kind: Pod
metadata: 
  name: vlm-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-RTX-A6000
            # - NVIDIA-GeForce-RTX-3090
            # - NVIDIA-A100-SXM4-80GB
  volumes:
  - name: git-secret
    secret:
      secretName: yixiang-key
      defaultMode: 256
  - name: dshm
    emptyDir:
      medium: Memory

  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/yg5d6/vlm
    command: ["/bin/sh", "-c"]
    args:
    - mkdir /root/.ssh/;
      cp /etc/ssh-key/ssh-privatekey /root/.ssh/id_ed25519;
      git config --global user.name  "Yixiang Gao";
      git config --global user.email "yixiangg310573@gmail.com";
      wandb login a9d4d981ca28ba6b6729e2a29464674ca243b891;
      huggingface-cli login --token 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;
      sleep infinity;
    resources:
      limits:
        memory: "32G"
        cpu: "4"
        nvidia.com/rtxa6000: "1"
        # nvidia.com/gpu: "1"
        # nvidia.com/a100: "1"
        ephemeral-storage: "50G"
      requests:
        memory: "32G"
        cpu: "4"
        nvidia.com/rtxa6000: "1"
        # nvidia.com/gpu: "1"
        # nvidia.com/a100: "1"
        ephemeral-storage: "50G"
    volumeMounts:
    - name: git-secret
      readOnly: true
      mountPath: /etc/ssh-key
    - name: dshm
      mountPath: /dev/shm
